# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TESTER <- function(n) {
    .Call(`_RCAFE_TESTER`, n)
}

#' @export
doFire <- function(tsf, fn_prob_tsf, diagonal = FALSE, max_ignition_attempts = 10L) {
    .Call(`_RCAFE_doFire`, tsf, fn_prob_tsf, diagonal, max_ignition_attempts)
}

#' @export
cafeSim <- function(initial_tsf, n_times, fn_prob_tsf, diagonal = FALSE, max_ignition_attempts = 10L, display_progress = TRUE) {
    .Call(`_RCAFE_cafeSim`, initial_tsf, n_times, fn_prob_tsf, diagonal, max_ignition_attempts, display_progress)
}

